services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_SERVICE_NAME=node-express-app
    depends_on:
      - otel-collector
    volumes:
      - otel-node-logs:/var/log/otel-node

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "4319:4319"
    depends_on:
      - loki
      - tempo
      - prometheus
    
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki-config.yml
    volumes:
      - ./loki-config.yml:/etc/loki-config.yml

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  tempo:
    image: grafana/tempo:latest
    ports:
      - "3200:3200"
      - "4320-4321:4317-4318"
    command: ["--config.file=/etc/tempo-config.yml"]
    volumes:
      - ./tempo-config.yml:/etc/tempo-config.yml
    
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  promtail:
    image: grafana/promtail:latest
    volumes:
      - otel-node-logs:/var/log/otel-node
      - ./promtail.yml:/etc/promtail/promtail.yml
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/promtail.yml
    restart: unless-stopped
    user: root
      
volumes:
  otel-node-logs:
    driver: local