server:
  http_listen_port: 3200
  # log_level: debug

distributor:
  receivers:
    otlp:
      protocols:
        http:

ingester:
  trace_idle_period: 10s
  max_block_duration: 5m

compactor:
  compaction:
    compacted_block_retention: 48h

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/traces
